version: 1.0.{build}
os: Visual Studio 2017
build_script:
- ps: >-
    .\build.ps1
artifacts:
- path: .\artifacts\*
deploy:
  provider: GitHub
  auth_token:
    secure: uXuMd3cu0eDp/Sz+XPaIVyROW36oLcxY0u72smAOAcn6LSViamfbxf9WpgcxQp1z
  artifact: artifacts\title-sequences.zip
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
